### ISSUE TITLE
Please upload a database dump in order to make tests

### ISSUE THREAD

**Issue by dannymontalvo** [Antonio-Laguna/Asterisk-nodejs-panel#1]
Hello,

Thanks for your contribution,

Currently i am starting on a similar project, I am trying to review your project in order to review and learn from you.

I think i will need a database dump in order to make it work, please if you can give me some tips in order to make it work i will be happy.

Danny.

**Comment by Antonio-Laguna** [comment]
Hey danny, 

Sorry for the delay but I was on holiday. 

I've pushed the table used in this. Hope it will be usefull for you.
